import json
from google import genai
from google.genai import types


# -----------------------------
# Function 1: Search by Driver & Grand Prix
# -----------------------------
get_penalty_by_driver_func = types.FunctionDeclaration(
    name="get_penalty_by_driver",
    description="Retrieve Formula 1 penalty decision chunks for a specific driver at a given Grand Prix.",
    parameters={
        "type": "object",
        "properties": {
            "driver": {
                "type": "string",
                "description": "Full name of the driver involved in the penalty (e.g., 'Carlos Sainz', 'Yuki Tsunoda').",
            },
            "grand_prix": {
                "type": "string",
                "description": "The Grand Prix name and year (e.g., '2025 Japanese Grand Prix').",
            },
            "search_content": {
                "type": "string",
                "description": "Search term or short description (e.g., 'causing a collision', 'unsafe release').",
            },
        },
        "required": ["driver", "grand_prix", "search_content"],
    },
)


def get_penalty_by_driver(driver, grand_prix, search_content, collection, embed_func):
    """Query penalty decisions by driver and race."""
    query_embedding = embed_func(search_content)
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=10,
        where={"driver": driver, "grand_prix": grand_prix},
    )
    return "\n".join(results["documents"][0]) if results["documents"] else "No results found."


# -----------------------------
# Function 2: Search by general content
# -----------------------------
get_penalty_by_search_content_func = types.FunctionDeclaration(
    name="get_penalty_by_search_content",
    description="Retrieve Formula 1 penalty decision chunks matching a given search term or description.",
    parameters={
        "type": "object",
        "properties": {
            "search_content": {
                "type": "string",
                "description": "Search text or description to find related penalty decisions (e.g., 'yellow flag infringement', 'safety car procedure').",
            },
        },
        "required": ["search_content"],
    },
)


def get_penalty_by_search_content(search_content, collection, embed_func):
    """Query penalty decisions based on general search terms."""
    query_embedding = embed_func(search_content)
    results = collection.query(query_embeddings=[query_embedding], n_results=10)
    return "\n".join(results["documents"][0]) if results["documents"] else "No results found."


# -----------------------------
# Combine all F1 tools
# -----------------------------
f1_penalty_tool = types.Tool(
    function_declarations=[
        get_penalty_by_driver_func,
        get_penalty_by_search_content_func,
    ]
)


# -----------------------------
# Function execution logic
# -----------------------------
def execute_function_calls(function_calls, collection, embed_func):
    """Execute the function calls generated by the LLM agent."""
    parts = []
    for function_call in function_calls:
        print("Function:", function_call.name)

        if function_call.name == "get_penalty_by_driver":
            print(
                "Calling function with args:",
                function_call.args["driver"],
                function_call.args["grand_prix"],
                function_call.args["search_content"],
            )
            response = get_penalty_by_driver(
                function_call.args["driver"],
                function_call.args["grand_prix"],
                function_call.args["search_content"],
                collection,
                embed_func,
            )
            print("Response:", response)
            parts.append(
                types.Part.from_function_response(
                    name=function_call.name,
                    response={"content": response},
                )
            )

        elif function_call.name == "get_penalty_by_search_content":
            print("Calling function with args:", function_call.args["search_content"])
            response = get_penalty_by_search_content(
                function_call.args["search_content"], collection, embed_func
            )
            print("Response:", response)
            parts.append(
                types.Part.from_function_response(
                    name=function_call.name,
                    response={"content": response},
                )
            )

    return parts
